apply plugin: 'com.android.application'

android {
    namespace rootProject.ext.android.applicationId
    compileSdk rootProject.ext.android.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId rootProject.ext.android.applicationId
        minSdk rootProject.ext.android.minSdkVersion
        targetSdk rootProject.ext.android.targetSdkVersion
        versionCode rootProject.ext.android.versionCode
        versionName rootProject.ext.android.versionName

        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        debug {
            buildConfigField("boolean", "LOG_DEBUG", "true")
            buildConfigField 'cn.byronlab.weather.util.StethoHelper', 'STETHO', 'new cn.byronlab.weather.DebugStethoHelper()'
        }

        release {
            buildConfigField("boolean", "LOG_DEBUG", "false")
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField 'cn.byronlab.weather.util.StethoHelper', 'STETHO', 'new cn.byronlab.weather.util.stetho.ReleaseStethoHelper()'
        }
    }
    buildFeatures { buildConfig true }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.13.2'

    implementation project(':library')
    implementation project(':widget')
    implementation project(':domain')

    implementation rootProject.ext.dependencies["SmartRefreshLayout"]
    implementation rootProject.ext.dependencies["SmartRefreshHeader"]

    implementation rootProject.ext.dependencies["butterknife"]
    annotationProcessor rootProject.ext.dependencies["butterknife-compiler"]

    implementation rootProject.ext.dependencies["dagger"]
    annotationProcessor rootProject.ext.dependencies["dagger-compiler"]

    implementation rootProject.ext.dependencies["retrofit2-fastjson-converter"]
}
